import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { UIProvider } from '@/components/Providers/NextUIProvider'
import NavbarComp from '@/components/Navbar'
import { SessionProvider } from '@/context/SessionContext'
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <SessionProvider>
          <UIProvider>
            <NavbarComp />
            {children}
          </UIProvider>
        </SessionProvider>
      </body>
    </html>
  )
}
